FROM python:3.9-slim-buster

WORKDIR /

COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt
RUN pip install docker
RUN apt-get update
RUN apt-get update && apt-get install -y aptitude
RUN aptitude install -y libpq-dev
RUN apt-cache search libpq-dev
RUN apt-get install libpq-dev
RUN pip install psycopg2-binary

COPY . /

CMD ["pytest", "test2.py"]
