#FROM python:3.9-alpine

#WORKDIR /


#COPY test.py .

#CMD ["pytest", "-vv", "test.py"] 


# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory to /app
WORKDIR /

# Copy the requirements file into the container at /app
COPY requirements.txt .


# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /

# Run pytest when the container launches
CMD ["pytest", "test.py"]
